# yaml-language-server: $schema=https://json.schemastore.org/cloudbuild.json
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-west1-docker.pkg.dev/turnkey-skill-461919-g3/image-registry/client-gateway",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/turnkey-skill-461919-g3/image-registry/client-gateway",
      ]
options:
  logging: CLOUD_LOGGING_ONLY